### ISSUE TITLE
limit activity types

### ISSUE THREAD

**Issue by hmoffatt** [matthewsnell/bulk-update-gear#3]
I needed to bulk-update all my Virtual Rides on Strava because they get auto-uploaded with the default bike from my virtual ride software, which is my outdoor bike and not the indoor bike...

It would be great if the activity types could be set in the form rather than always doing ['Ride', 'EBikeRide', 'VirtualRide'].

I made a local hack and ran the bulk update I needed. Great tool, thanks for this!

**Comment by matthewsnell** [comment]
Thanks for opening this issue. I think this is a great idea. I'll add it into the next update.

**Comment by hmoffatt** [comment]
I’d love to have an agent running bulk updates on a regular schedule (ie every day fix my virtual rides of the last 24 hours), but that’s a bit bigger than this. I can open another issue if it’s of interest.

**Comment by matthewsnell** [comment]
If you open another issue and add a bit more detail about how this idea would work that would be great.

**Comment by hmoffatt** [comment]
Thanks! You have a small typo: "only update **virutal** activities"
